# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ProcessingSystem/ProcessingSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem || ORIG_REF_NAME==ProcessingSystem}]

# IP: bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_processing_system7_0_0 || ORIG_REF_NAME==ProcessingSystem_processing_system7_0_0}]

# IP: bd/ProcessingSystem/ip/ProcessingSystem_proc_sys_reset_0_0/ProcessingSystem_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_proc_sys_reset_0_0 || ORIG_REF_NAME==ProcessingSystem_proc_sys_reset_0_0}]

# XDC: bd/ProcessingSystem/ProcessingSystem_ooc.xdc
