# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/daniel/Schreibtisch/Git/Zybo-Linux/Yocto/poky/build/tmp/work-shared/gcc-4.9.1-r0/gcc-4.9.1/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
