# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/System.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_ps7_0_100M_0 || ORIG_REF_NAME==System_rst_ps7_0_100M_0}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_ps7_0_100M_0 || ORIG_REF_NAME==System_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_rst_ps7_0_100M_0 || ORIG_REF_NAME==System_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/System/System_ooc.xdc
