# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.cache/wt [current_project]
set_property parent.project_path /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/hdl/System_wrapper.vhd
add_files /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/System.bd
set_property used_in_implementation false [get_files -all /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/ip/System_rst_ps7_0_100M_0/System_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/System_ooc.xdc]
set_property is_locked true [get_files /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/sources_1/bd/System/System.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/constrs_1/new/System.xdc
set_property used_in_implementation false [get_files /home/daniel/Schreibtisch/Git/Zybo_Linux/Vivado/Zybo/Zybo.srcs/constrs_1/new/System.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top System_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef System_wrapper.dcp

catch { report_utilization -file System_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb }
